# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  fr3_finger_joint1:
    has_velocity_limits: true
    max_velocity: 0.20000000000000001
    has_acceleration_limits: true
    max_acceleration: 1.0
  fr3_finger_joint2:
    has_velocity_limits: true
    max_velocity: 0.20000000000000001
    has_acceleration_limits: true
    max_acceleration: 1.0
  fr3_joint1:
    has_velocity_limits: true
    max_velocity: 2.6200000000000001
    has_acceleration_limits: true
    max_acceleration: 1.0
  fr3_joint2:
    has_velocity_limits: true
    max_velocity: 2.6200000000000001
    has_acceleration_limits: true
    max_acceleration: 1.0
  fr3_joint3:
    has_velocity_limits: true
    max_velocity: 2.6200000000000001
    has_acceleration_limits: true
    max_acceleration: 1.0
  fr3_joint4:
    has_velocity_limits: true
    max_velocity: 2.6200000000000001
    has_acceleration_limits: true
    max_acceleration: 1.0
  fr3_joint5:
    has_velocity_limits: true
    max_velocity: 5.2599999999999998
    has_acceleration_limits: true
    max_acceleration: 1.0
  fr3_joint6:
    has_velocity_limits: true
    max_velocity: 4.1799999999999997
    has_acceleration_limits: true
    max_acceleration: 1.0
  fr3_joint7:
    has_velocity_limits: true
    max_velocity: 5.2599999999999998
    has_acceleration_limits: true
    max_acceleration: 1.0